// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCftrCqjldaImdcMKMt9WIFI_VBDCGaUa4',
    appId: '1:740797770414:web:5f0afdd7bed22a816f9b3f',
    messagingSenderId: '740797770414',
    projectId: 'student-registration-app-64179',
    authDomain: 'student-registration-app-64179.firebaseapp.com',
    storageBucket: 'student-registration-app-64179.firebasestorage.app',
    measurementId: 'G-KY9836T565',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsIEYIxKl4yJxGVAHBoGYSFfGNHrZ0cI4',
    appId: '1:740797770414:android:c59d5f5cf3643f946f9b3f',
    messagingSenderId: '740797770414',
    projectId: 'student-registration-app-64179',
    storageBucket: 'student-registration-app-64179.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC63cXBfIlQzkGRCUt-_I7i3Ww9oQ8gBuc',
    appId: '1:740797770414:ios:e460660ad613c02c6f9b3f',
    messagingSenderId: '740797770414',
    projectId: 'student-registration-app-64179',
    storageBucket: 'student-registration-app-64179.firebasestorage.app',
    iosBundleId: 'com.example.studentRegistrationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC63cXBfIlQzkGRCUt-_I7i3Ww9oQ8gBuc',
    appId: '1:740797770414:ios:e460660ad613c02c6f9b3f',
    messagingSenderId: '740797770414',
    projectId: 'student-registration-app-64179',
    storageBucket: 'student-registration-app-64179.firebasestorage.app',
    iosBundleId: 'com.example.studentRegistrationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCftrCqjldaImdcMKMt9WIFI_VBDCGaUa4',
    appId: '1:740797770414:web:bd81189bc35b9d116f9b3f',
    messagingSenderId: '740797770414',
    projectId: 'student-registration-app-64179',
    authDomain: 'student-registration-app-64179.firebaseapp.com',
    storageBucket: 'student-registration-app-64179.firebasestorage.app',
    measurementId: 'G-MQ0SLKL7YZ',
  );
}
